---
title: "Power Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(brms)
library(broom)
library(ggthemes)
library(lme4)

# langcog package is installed by running
# install.packages("devtools")
# devtools::install_github("langcog/langcog")

library(langcog)



```

# load data
```{r}
read_plus <- function(flnm) {
    read_csv(flnm, skip = 3) %>% 
        mutate(filename = flnm, 
               trial = 1:length(SampleSound),
               RT = as.character(RT))
}


raw_data <- list.files(path = "../Data/Testing/",
                       pattern = "*.csv",
                       full.names = T) %>% 
  map_df(~read_plus(.))

data <- raw_data %>%
  filter(trial != 1)%>%
  mutate(correct = ifelse(Correct_1 == "YES" | Correct_1 == "YES (R)", 1, 0),
         shape_combination  = paste(Correct,Foil1, sep = "_"), 
         session = as.numeric(factor(filename)), 
         condition = ifelse(grepl("Slide", Correct) | grepl("shape", Correct),"test", "filler"),
         RT = as.numeric(RT))%>%
  na.omit(correct)

```

# Descriptives

## No Trials

```{r}
data %>%
  group_by(condition)%>%
  summarise(n())
```

## RT

```{r}
rt_data <- data%>%
  mutate(outlier = ifelse(RT>5999, "yes", "no"),
         correct = ifelse(correct == 1, "correct", "wrong"))

ggplot(rt_data, aes(x = condition, y = RT, col = correct, pch = correct))+
  geom_jitter(alpha = .7, width = .2, height = 0)+
  ylim(0,6000)+
  ylab("Reaction Time")+
  scale_color_ptol()+
  theme_minimal()
```

# visualize data overall

```{r}

# CI based on non-parametric bootstrap of the data
plot <- data%>%
  group_by(condition)%>%
  multi_boot_standard(col = "correct")

ggplot(plot, aes(x = condition))+
  geom_hline(yintercept = 0.5, lty = 2)+
  geom_pointrange(aes(y = mean, ymax = ci_upper, ymin = ci_lower, col = condition))+
  ylim(0,1)+
  ylab("Proportion correct")+
  scale_color_ptol()+
  theme_minimal()


```
# data by session

```{r}
plot1 <- data%>%
  group_by(session,condition)%>%
  multi_boot_standard(col = "correct")

ggplot(plot1, aes(x = session, col = condition))+
  geom_hline(yintercept = 0.5, lty = 2)+
  geom_pointrange(aes(y = mean, ymax = ci_upper, ymin = ci_lower))+
  geom_line(aes(y= mean, col = condition))+
  ylim(0,1)+
  facet_grid(~condition)+
  ylab("Proportion correct")+
  scale_color_ptol()+
  theme_minimal()
```

# test trials, round vs. edgy

```{r}
plot2 <- data%>%
  filter(condition == "test")%>%
  mutate(test_shape = ifelse(grepl("ESlide", Correct) | grepl("Eshape", Correct),"edgy", "round"))%>%
  group_by(test_shape)%>%
  multi_boot_standard(col = "correct")

ggplot(plot2, aes(x = test_shape, col = test_shape))+
  geom_hline(yintercept = 0.5, lty = 2)+
  geom_pointrange(aes(y = mean, ymax = ci_upper, ymin = ci_lower))+
  geom_line(aes(y= mean, col = test_shape))+
  ylim(0,1)+
  ylab("Proportion correct")+
  scale_color_ptol()+
  theme_minimal()
```

# Test Models
```{r}
test_data <- data %>%
  filter(condition == "test")
```

# Test: Bayesian

```{r}
bm_test <- brm(correct ~ 1 + (1|SampleSound) + (1 | shape_combination),
          data = test_data,
          family = bernoulli(),
          cores = 4,
          chains = 4,
          iter = 10000,
          control = list(adapt_delta = 0.95))

bm_test
```

# Test: Frequentist

```{r}
fm_test <- glmer(correct ~ 1 + (1|SampleSound) + (1 | shape_combination), 
              data = test_data, 
              family = binomial, 
              control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))

summary(fm_test)

```

# Filler Models
```{r}
filler_data <- data %>%
  filter(condition == "filler")
```

# Filler: Bayesian

```{r}
bm_filler <- brm(correct ~ 1 + (1|SampleSound) + (1 | shape_combination),
          data = filler_data,
          family = bernoulli(),
          control = list(adapt_delta = 0.95))

bm_filler
```


# Test: Frequentist

```{r}
fm_filler <- glmer(correct ~ 1 + (1|SampleSound) + (1 | shape_combination), 
              data = filler_data, 
              family = binomial, 
              control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))

summary(fm_filler)

```
